# Generated by Django 3.0.14 on 2022-07-23 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('name_product', models.CharField(max_length=100)),
                ('QTT_Entree', models.CharField(max_length=100)),
                ('Prix_Achat', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('admin_comment', models.CharField(default='Nothing', max_length=200)),
                ('asked_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('capacity_Stock', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('reference', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('QTT_Stock', models.CharField(max_length=100)),
                ('Prix_Stock', models.CharField(max_length=100)),
                ('QTT_Entree', models.CharField(max_length=100)),
                ('Prix_Achat', models.CharField(max_length=100)),
                ('QTT_Sortie', models.CharField(max_length=100)),
                ('Prix_Vente', models.CharField(max_length=100)),
                ('Fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Fournisseur')),
                ('Warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Warehouse')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.category')),
            ],
        ),
    ]
