# Generated by Django 3.0.14 on 2022-07-28 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=100, null=True)),
                ('Prenom', models.CharField(max_length=100, null=True)),
                ('phone', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('RIB', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NumFact', models.CharField(max_length=100, null=True)),
                ('NumCommande', models.CharField(max_length=100, null=True)),
                ('date', models.DateTimeField(null=True)),
                ('Mode_Paiement', models.CharField(choices=[('Especes', 'Especes'), ('Cheque', ' Cheque'), ('Versement', 'Versement'), (' Virement', ' Virement'), ('Autre', 'Autre')], max_length=100, null=True)),
                ('Etat', models.CharField(choices=[('Non Paye', 'Non Paye'), ('Payé', 'Payé'), ('Verse', 'Verse'), ('Annulé', 'Annulé')], max_length=100, null=True)),
                ('TVA', models.CharField(max_length=100, null=True)),
                ('QTT', models.CharField(max_length=100, null=True)),
                ('Prix', models.CharField(max_length=100, null=True)),
                ('Total', models.CharField(max_length=100, null=True)),
                ('Produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Produit')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Client')),
            ],
        ),
    ]
