# Generated by Django 3.0.14 on 2022-07-31 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_client_facture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facture',
            name='NumCommande',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='NumFact',
        ),
    ]
